iter1
NikolosHGW/gophermart pull request #1
Opened 2024-05-05 07:30 UTC by NikolosHGW

2024-05-07 20:35 UTC, Bazys requested changes
тесты?
если что то не понятно в ТЗ, записывайся на 1-1

2024-05-08 03:38 UTC, NikolosHGW commented
> тесты? если что то не понятно в ТЗ, записывайся на 1-1

![image](https://github.com/NikolosHGW/gophermart/assets/44165422/3d01b4be-22ea-477f-a49d-8560cce29537)

2024-05-26 20:42 UTC, Bazys requested changes
пара вопросов. Основное, это все таки повнимательнее с локами, это слишком мощный инструмент.

2024-05-26 20:42 UTC, Bazys commented on internal/app/service/accrual.go
> +		cancelFunc()
Пробросить отмену сквозь 4 функции, что бы тут ее вызвать, это наверное говорит о не совсем корректном использовании

2024-05-26 20:42 UTC, Bazys commented on internal/app/service/accrual.go
> +			mutex.Lock()
а точно здесь нужен лок?
У тебя ниже по стеку этой функции есть слип на то время, которое отдал черный ящик, и никакая другая горутина не сможет работать с сущностями что взяты в лок.
Каждый вызов `initRequest` создает новый контекст и делает новый запрос, потенциально блокируя другие операции.
Вместо использования мьютекса рассмотри возможность использования канала

2024-05-26 20:42 UTC, Bazys commented on internal/app/service/accrual.go
> +		ctx, cancelFunc := context.WithCancel(context.Background())
дублирующийся код.
Я бы переписал на бесконечном цикле

	for {
		select {
		case <-ctx.Done():
			return
		case <-retryTicker.C:
			a.initRequest(ctx)
		}
	}

2024-05-26 20:42 UTC, Bazys commented on internal/domain/usecase/claims.go
> +type Claims struct {
это точно usecase?

2024-05-26 20:42 UTC, Bazys commented on internal/app/service/accrual.go
> +	ordersChan := a.generator(ctx, orders)
если на 69 строке была ошибка - будет пустой массив. А ты все равно породишь горутину и канал. Зачем делать лишнюю для работу GC?

2024-05-26 20:42 UTC, Bazys commented on internal/app/service/accrual.go
> +	if resp.StatusCode == http.StatusTooManyRequests {
эти ифчики можно переписать на свич (тру гошный стиль)

2024-05-26 20:42 UTC, Bazys commented on internal/app/service/accrual.go
> +	resp, err := http.Get(a.accrualAddress + "/api/orders/" + orderNumber)
контекст есть, так почему бы не использовать http.NewRequestWithContext

2024-05-30 04:27 UTC, NikolosHGW commented on internal/app/service/accrual.go
> +		cancelFunc()
+

2024-05-30 04:27 UTC, NikolosHGW commented on internal/app/service/accrual.go
> +			mutex.Lock()
+

2024-05-30 04:27 UTC, NikolosHGW commented on internal/app/service/accrual.go
> +		ctx, cancelFunc := context.WithCancel(context.Background())
+

2024-05-30 04:27 UTC, NikolosHGW commented on internal/app/service/accrual.go
> +	ordersChan := a.generator(ctx, orders)
+

2024-05-30 04:27 UTC, NikolosHGW commented on internal/app/service/accrual.go
> +	if resp.StatusCode == http.StatusTooManyRequests {
+

2024-05-30 04:27 UTC, NikolosHGW commented on internal/app/service/accrual.go
> +	resp, err := http.Get(a.accrualAddress + "/api/orders/" + orderNumber)
+

2024-05-30 04:33 UTC, NikolosHGW commented on internal/domain/usecase/claims.go
> +type Claims struct {
+

2024-06-01 22:23 UTC, Bazys approved these changes
Из-за названия файлов уже не буду заворачивать, в Го применяется snake-case для названия файлов

2024-06-02 05:35 UTC, merged